server:
  port: 8081
  servlet:
    context-path: /media

application:
  base-folder: E:\\Programming\\CodeTechOutput

spring:
  servlet:
    multipart:
      max-file-size: 3500MB
      max-request-size: 4000MB
