server:
  port: 8081
  servlet:
    context-path: /media

application:
  version: @project.version@
  base-folder: /home

spring:
  servlet:
    multipart:
      max-file-size: 3500MB
      max-request-size: 4000MB
